package Exception;

public class Exception {
////	public void show() {
////		System.out.println("This is custom class");
////	}
//}
//	class main{
//		public static void main(String[] args) {
////			Exception my = new Exception();
////			my.show();
//			int[] arr = new int[4];
////			int i = arr[4];
//			System.out.println("I want to execute");
//		}
//static void fun()
//{
//	try {
//		throw new NullPointerException("demo");
//	}
//	catch (NullPointerException e) {
//		System.out.println("Caught inside fun().");
//		throw e; // rethrowing the exception
//	}
//}
//
//	public static void main(String args[])
//	{
//		try {
//			fun();
//		}
//		catch (NullPointerException e) {
//			System.out.println("Caught in main.");
//		}
//	}
public static void main(String[] args)
	 throws InterruptedException
{
	Thread.sleep(10);
	System.out.println("Hello Geeks");
}
	}


